pulp_version: latest
image_source: quay.io
pulp_port: 8080
pulp_host_dir: /home/pulp/pulp

pulp_api_replicas: 2
pulp_content_replicas: 2
pulp_worker_replicas: 2
pulp_gunicorn_timeout: 90

pulp_uid: 1001

pulp_db_name: pulp
pulp_db_user: pulp
pulp_redis_port: 6379
